modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/mries92/Bounce/issues"
showAsResourcePack=false
license="MIT"

[[mods]]
    modId="bounce"
    version="1.0.0-alpha"
    displayName="Bounce"
    logoFile="wooden_pogo_stick.png"
    authors="REEEfactor"
    description="Adds pogo sticks!"

    [[dependencies.bounce]]
        modId="forge"
        mandatory=true
        versionRange="[34,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.bounce]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.5]"
        ordering="NONE"
        side="BOTH"